# Docdata-order RuboCop configuration

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'


Layout/LineLength:
  Enabled: false


Metrics/AbcSize:
  Max: 58

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false


RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 41

RSpec/MultipleExpectations:
  Max: 10


Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false
